config/routes.rb
Rails.application.routes.draw do

  root to: 'application#home'
  get '/about' => 'application#about'

  resources :blog, param: :headline
  resources :designs
  resources :programs

  patch '/blog' => 'blog#update'

  devise_for :users

end

app/models/design.rb
class Design < ActiveRecord::Base
  has_one :gallery, :dependent => :destroy

  def gallery=(gallery_attributes)
    if self.gallery
      self.gallery.name = gallery_attributes[:name]
      self.gallery.save
    else
      self.build_gallery(name: gallery_attributes[:name])
      self.gallery.save
    end
  end

  def add_photos(photos)
    photos.sort_by {|p| p.original_filename}.each do |pic|
      self.gallery.photos << Photo.create(pic: pic)
    end
  end

  #for nav between designs

  def self.get_next(design)
     self.where("display_rank > ?", design.display_rank).order("display_rank").first
  end

  def self.get_prev(design)
     self.where("display_rank < ?", design.display_rank).order("display_rank DESC").first
  end

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :photos, :dependent => :destroy

  belongs_to :design
  belongs_to :post
  belongs_to :program
end

app/models/icon.rb
class Icon < ActiveRecord::Base
  has_attached_file :icon, styles: { thumb: "40x40" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :icon, content_type: /\Aimage\/.*\Z/

  has_many :posts
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :pic, styles: { thumb: "111x111#", medium_horiz: "330x220#", large_horiz: "880x592"}, :export => {:quality => 100}
  validates_attachment_content_type :pic, content_type: /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base
  include FriendlyId
  friendly_id :headline, use: :slugged

  has_one :gallery, :dependent => :destroy
  belongs_to :icon

  def gallery=(gallery_attributes)
    if self.gallery
      self.gallery.name = gallery_attributes[:name]
      self.gallery.save
    else
      self.build_gallery(name: gallery_attributes[:name])
      self.gallery.save
    end
  end

  def add_photos(photos)
    photos.sort_by {|p| p.original_filename}.each do |pic|
      self.gallery.photos << Photo.create(pic: pic)
    end
  end

  def icon_attributes=(icon_attributes)
    if icon_attributes["name"] != "" && !icon_attributes["icon"].nil?
      self.icon = Icon.find_or_create_by(name: icon_attributes["name"])
      if self.icon.icon_file_name.nil?
        self.icon.icon = icon_attributes["icon"]
      end
    end
    self.icon.save unless self.icon.nil?
  end

  # for nav between posts

  def self.get_next(post)
    self.where("created_at > ?", post.created_at).order("created_at").first
  end

  def self.get_prev(post)
    self.where("created_at < ?", post.created_at).order("created_at DESC").first
  end


end

app/models/post_image.rb
class PostImage < ActiveRecord::Base
  belongs_to :post
end

app/models/program.rb
class Program < ActiveRecord::Base
  has_one :gallery, :dependent => :destroy

  def gallery=(gallery_attributes)
    if self.gallery
      self.gallery.name = gallery_attributes[:name]
      self.gallery.save
    else
      self.build_gallery(name: gallery_attributes[:name])
      self.gallery.save
    end
  end

  def add_photos(photos)
    photos.sort_by {|p| p.original_filename}.each do |pic|
      self.gallery.photos << Photo.create(pic: pic)
    end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def home
  end

  def about
  end

  def protohome
  end
  
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @posts = Post.all
    @posts = @posts.sort_by {|post| post.created_at}.reverse
  end

  def new
    @post = Post.new()
    @post.build_icon
    @post.build_gallery
  end

  def create
    @post = Post.new(post_params)
    @post.add_photos(params[:photos]) unless params[:photos].nil?
    if params[:icon_id]
      @post.icon = Icon.find_by[:icon_id]
    end
    @post.save
    redirect_to blog_path(@post)
  end

  def edit
    @post = Post.find_by(slug: params[:headline])
    @post.build_icon unless @post.icon
    @post.build_gallery unless @post.gallery
  end

  def update
    @post = Post.find_by(slug: params[:headline])
    if post_params[:icon_id]
      @post.icon = Icon.find_by(id: post_params[:icon_id])
    end
    @post.update(post_params)
    @post.add_photos(params[:photos]) unless params[:photos].nil?
    @post.save
    redirect_to blog_path(@post)
  end

  def show
    @post = Post.find_by(slug: params[:headline])
    @next_post = Post.get_next(@post)
    @prev_post = Post.get_prev(@post)
    respond_to do |f|
      f.html { render :show }
      f.json { render json: @post}
    end
  end

  def destroy
    @post = Post.find_by(slug: params[:headline])
    @post.destroy
    redirect_to blog_index_path
  end

    private

    def post_params
      params.require(:post).permit(:headline, :date, :content, :icon_id, :created_at,
                                   :icon_attributes => [:name, :icon], :gallery=> [:name])
    end

end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @designs = Design.all.sort_by {|d| d.display_rank}
  end

  def new
    @design = Design.new
    @design.build_gallery
  end

  def create
    @design = Design.new(design_params)
    @design.add_photos(params[:photos]) unless params[:photos].nil?
    @design.save
    redirect_to design_path(@design)
  end

  def show
    @design = Design.find_by(id: params[:id])
    @prev_design = Design.get_prev(@design)
    @next_design = Design.get_next(@design)
  end

  def edit
    @design = Design.find_by(id: params[:id])
    @design.build_gallery unless @design.gallery
  end

  def update
    @design = Design.find_by(id: params[:id])
    if params[:design][:gallery]["replace photos"] == 'true'
      @design.gallery.photos.delete_all
    end
    @design.update(design_params)
    @design.add_photos(params[:photos]) unless params[:photos].nil?
    redirect_to design_path(@design)
  end

  def destroy
    @design = Design.find_by(id: params[:id])
    @design.destroy
    redirect_to designs_path
  end

    private

    def design_params
        params.require(:design).permit(:title, :client_name, :description, :long_desc,
                                       :display_rank, :gallery => [:name])
    end

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @programs = Program.all.sort_by {|p| p.display_rank}
  end

  def new
    @program = Program.new
    @program.build_gallery
  end

  def create
    @program = Program.new(program_params)
    @program.add_photos(params[:photos]) unless params[:photos].nil?
    @program.save
    redirect_to programs_path
  end


  def show
    @program = Program.find_by(id: params[:id])
  end

  def edit
    @program = Program.find_by(id: params[:id])
    @program.build_gallery unless @program.gallery
  end


  def update
    @program = Program.find_by(id: params[:id])
    if params[:program][:gallery]["replace photos"] == 'true'
      @program.gallery.photos.delete_all
    end
    @program.update(program_params)
    @program.add_photos(params[:photos]) unless params[:photos].nil?
    @program.save
    redirect_to programs_path
  end

  def destroy
    @program = Program.find_by(id: params[:id])
    @program.destroy
    redirect_to programs_path
  end


    private

    def program_params
        params.require(:program).permit(:title, :description, :link, :demo,
                                        :display_rank, :gallery => [:name])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/design_helper.rb
module DesignHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/application/about.html.erb
<% content_for :about_nav do %>
  <%=link_to image_tag('don.png', id:'donpic_about'), root_path %>
<% end %>

<div id="navbar" style='position: fixed; 
  width: 100%;
  top: 40px;
  left: 0px; z-index: 9998;'>
    <nav>
      <div class="links">
        <%=link_to 'design', designs_path%>
        <%=link_to 'programming', programs_path%>
        <%=link_to 'blog', blog_index_path%>
        <%=link_to 'about',  about_path %>
      </div>
    </nav>
</div>

<div class="logo_type_not_home" id='about_logo'>
  <h1>life</h1>
  <div id='hr_holder__5'><hr></div>
</div>

<div id='about_wrapper'>
  <br>
  <p>Well, hello there world!</p>

  <p>I'm an arts lover, designer and full stack web developer. Future code ninja. Unashamed lover of jQuery. Great cook and mediocre guitar player. Game enthusiast. Book junkie.</p>

  <p>My passion is creating and improving things. I love to think both creatively and analytically to acheive a goal.</p>

  <p>Design and Programming are my bread and butter because they use both sides of my brain. I am comfortable leading or working as part of a team as well as tackling projects on my own when the situation calls for it.

  <p>Above all, I love to learn new things and grow as a result.</p>

  <ul>
    <li>Email: <%= mail_to 'febbraio.don@gmail.com' %></li>
    <li>Resume: <%= link_to "Don's Resume", 'https://learn.co/febbraiod/resume', :target => "_blank" %></li>
    <li>Github: <%= link_to 'febbraiod', 'https://github.com/febbraiod', :target => "_blank" %></li>
    <li>Linkedin: <%= link_to 'donfebbraio' , 'https://www.linkedin.com/in/donfebbraio', :target => "_blank" %></li>
    <li>Twitter: <%= link_to '@Donnief3', 'https://twitter.com/Donnief3', :target => "_blank" %></li>
  </ul>

</div>

app/views/application/home.html.erb
<% content_for :home_nav do %>
    <div id='nav_tree__container'>
      <div id='about_link'><%=link_to image_tag('sig_pic.png', id:'donpic_homepage'), about_path %>
      <%=link_to image_tag('sig_pic_hover.png', id:'donpic_homepage_hover'), about_path %></div>
      <%=link_to designs_path do%>
        <div class='link_holder' id='design_link'>design</div>
      <%end%>
      <%=link_to programs_path do%>
      <div class='link_holder' id='programming_link'>programming</div>
      <%end%>
      <%=link_to blog_index_path do%>
      <div class='link_holder' id ='blog_link'>blog</div>
      <%end%>
    </div>
<% end %>

<div class="wrapper">

<div class="logo_type">
  <div id="logo_type_1">
    <h1><a id='home_head' href='/designs'><span class='don_design'>design</span></a></h1> 
    <h1><a id='home_head' href='/programs'><span class='don_program'>program</span></a></h1>
  </div>

  <div id="logo_type_2">  
    <h1><a id='rinse_link' href='/blog'><span class='don_rinse'>rinse</span></a></h1>
    <h1><a id='repeat_link' href='/about'>repeat</a></h1>
  </div>
</div>

</div>

app/views/blog/edit.html.erb
<div class="wrapper">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<h3>Edit: <%=@post.headline%></h3>

<%= link_to 'delete post', blog_path(@post), :method => :delete %><br><br><br>

<%=form_for @post, url: blog_path(@post) do |f| %>

<%=f.label :headline %><br>
<%=f.text_field :headline %>
<br>
<%=f.label :date %><br>
<%=f.text_field :date %>
<br>
<%=f.label :content %><br>
<%=f.text_area :content %>
<br>
<%=f.label :created_at %>
<%=f.datetime_select :created_at%>
<br>

<h5>Icon:</h5>
    <%= f.collection_select :icon_id, Icon.all, :id, :name, include_blank: true %>
<h5>New Icon:</h5>
    <%= f.fields_for :icon do |ico| %>
      <%= ico.label :name %><br>
      <%= ico.text_field :name %><br>
      <%= ico.label :icon %><br>
      <%= ico.file_field :icon %>
    <% end %>

<h5>Gallery Images:</h5>
  <%= f.fields_for :gallery do |gal|%>
    <%= gal.label :name %><br>
    <%= gal.text_field :name%><br>
    <%= gal.label :photos %><br>
    <%= file_field_tag "photos[]", type: :file, multiple:true %>
  <% end %>    
<%=f.submit%>
<%end%>

</div>

app/views/blog/index.html.erb
<div id="white_navbar" style='position: fixed; 
  width: 100%;
  top: 75px;
  left: 0px; z-index: 9998;'>
    <nav>
      <div class="links">
        <%=link_to 'design', designs_path%>
        <%=link_to 'programming', programs_path%>
        <%=link_to 'blog', blog_index_path%>
        <%=link_to 'about',  about_path %>
      </div>
    </nav>
</div>

<%= image_tag('blog_pencil.jpg', style: 'width: 100%;') %>

<div class="logo_type_not_home">
    <h1>blog</h1>
    <div id='hr_holder__4'><hr></div>
</div>

  <div class="wrapper">

    <% @posts.each do |post| %>
      <h3 id='index_headline'><%=link_to post.headline, blog_path(post)%></h3>
      <%if post.icon && post.icon.icon.url(:thumb) != '/images/thumb/missing.png' %>
        <%= image_tag post.icon.icon.url, class: 'title_icon', id: 'index_headline_icon' %>
      <%end%>
      <h4><%=post.date%></h4>
      <p class='post_wrapper__index' id=<%="post_" + "#{post.slug}"%>><%= truncate(post.content, length: 280) {link_to "more", blog_path(post)} %></p>
      <br>
    <%end%>

    <br>

  </div><!--.wrapper-->

app/views/blog/new.html.erb
<div class="wrapper">
<h1>Hi Don!</h1>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%=form_for @post, url: blog_index_path, html: { multipart: true } do |f| %>

<%=f.label :headline %><br>
<%=f.text_field :headline %>
<br>
<%=f.label :date %><br>
<%=f.text_field :date %>
<br>
<%=f.label :content %><br>
<%=f.text_area :content %>
<br>
<%=f.label :created_at %>
<%=f.datetime_select :created_at%>
<br>

<h5>Icon:</h5>
    <%= f.collection_select :icon_id, Icon.all, :id, :name, include_blank: true %>
<h5>New Icon:</h5>
    <%= f.fields_for :icon do |ico| %>
      <%= ico.label :name %><br>
      <%= ico.text_field :name %><br>
      <%= ico.label :icon %><br>
      <%= ico.file_field :icon %>
    <% end %>

<h5>Gallery Images:</h5>
  <%= f.fields_for @post.gallery do |gal|%>
    <%= gal.label :name %><br>
    <%= gal.text_field :name%><br>
    <%= gal.label :photos %><br>
    <%= file_field_tag "photos[]", type: :file, multiple:true %>
  <% end %>    

<%=f.submit%>
<%end%>

</div>

app/views/blog/show.html.erb
<div id="white_navbar" style='position: fixed; 
  width: 100%;
  top: 75px;
  left: 0px; z-index: 9998;'>
    <nav>
      <div class="links">
        <%=link_to 'design', designs_path%>
        <%=link_to 'programming', programs_path%>
        <%=link_to 'blog', blog_index_path%>
        <%=link_to 'about',  about_path %>
      </div>
    </nav>
</div>

<%= image_tag('blog_pencil.jpg', style: 'width: 100%;') %>

<div class="logo_type_not_home">
  <h1 id='postdate'><%=@post.date%></h1> 
</div>

<div class="post_wrapper">

  <%if @post.icon && @post.icon.icon.url(:thumb) != '/images/thumb/missing.png'%>
    <h3 id='post_headline_with_icon'><%=@post.headline%></h3>
    <%= image_tag @post.icon.icon.url, class: 'title_icon', id: 'headline_icon' %>
    <br>
  <%else%>
    <h3 id='post_headline'><%=@post.headline%></h3>
  <%end%>
  <div class='post_content'>
    <p><%= simple_format(@post.content, {}, :sanitize => false)%></p>
    <%= link_to image_tag('DonPrevButton.png', size: "30x30", id: 'prev_icon', style: 'display: initial;'), blog_path(@prev_post), class: 'prev_link'  if @prev_post%>
    <%= link_to image_tag('DonNextButton.png', size: "30x30", id: 'next_icon', style: 'display: initial;'), blog_path(@next_post), style: 'float: right', class: 'next_link' if @next_post%>
    <%= link_to image_tag('hoverDonPrevButton.png', size: "30x30", id: 'hover_prev_icon', style:'display: none;'), blog_path(@prev_post), class: 'prev_link' if @prev_post%>
    <%= link_to image_tag('hoverDonNextButton.png', size: "30x30", id: 'hover_next_icon', style:'display: none;'), blog_path(@next_post), style: 'float: right; margin-bottom: 100px;', class: 'next_link' if @next_post%>
    <br>
    <%if current_user %>
      <%= link_to 'edit post', edit_blog_path(@post), id: 'program_edit', style: 'margin-bottom: 100px;'%>
    <%end%>
    <br>
  </div>

  <div class='post_gallery'>

    <%if @post.gallery%>
      <%@post.gallery.photos.each_with_index do |img, i|%>
        <%= image_tag img.pic.url, class: "post_image post_image_#{i + 1}" %>
      <%end%>
    <%end%>
    <p style='visibility: hidden;'>.</p>
  </div>

</div>

app/views/designs/index.html.erb
<div id="white_navbar" style='position: fixed; 
  width: 100%;
  top: 75px;
  left: 0px; z-index: 9998;'>
    <nav>
      <div class="links">
        <%=link_to 'design', designs_path%>
        <%=link_to 'programming', programs_path%>
        <%=link_to 'blog', blog_index_path%>
        <%=link_to 'about',  about_path %>
      </div>
    </nav>
</div>

<%= image_tag('digi-design.jpg', style: 'width: 100%;') %>

<div class="logo_type_not_home" id='design_logo'>
    <h1>design</h1>
    <div id='hr_holder__1'><hr></div>
    <div id='hr_holder__2'><hr></div>
</div>

<div class="design_wrapper__index">
  <%@designs.each_with_index do |d, idx|%>
    <div class='design_container'>
      <%if d.gallery%>
        <div class='thumb_container__index'>
          <% d.gallery.photos.sort_by {|pic| pic.pic_file_name}.each do |img| %>
            <div class='thumb_box__index'>
              <%= link_to image_tag(img.pic.url, class: 'thumb__index'), design_path(d) %>
            </div>
          <%end%>
        </div>
      <%end%>
      <div class='design_desc__index'>  
        <%= d.description %><br>
        <%= link_to d.title, design_path(d) %> <small>for <%= d.client_name %></small>
      </div>
    </div>
    <br>
    <br>
    <br>
  <% end %>

  <br>
  <br>
  <br>
</div>

app/views/designs/new.html.erb
<div class="wrapper">
  <h1>Hi Don!</h1>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= render "design_form" %>

</div>

app/views/designs/show.html.erb
<!-- needs better responsive css for widths less than 800px -->

<% content_for :design_show do %>
  <%=link_to image_tag('sig_pic.png', id:'donpic_down'), root_path %>
<% end %>

<% photos = @design.gallery.photos.sort_by {|pic| pic.pic_file_name} %>

<% if photos.length > 4 %>
  <div class='design_wrapper_2'>
<% else %>
  <div class='design_wrapper'>
<% end %>

<%= link_to 'edit', edit_design_path(@design), class: 'edit_link' unless !current_user%> <!-- if admin -->

<% if photos.length > 4 %>
  <div class="logo_type_not_home__design_show_2">
<% else %>
  <div class="logo_type_not_home__design_show_1">
<% end %>
    <h1 id='title_headline'><%= @design.title %></h1>
  </div>

  <div class='design_container'>
    <div class='short_desc'>
      <%= @design.description %><br>
      <% if !@design.client_name.empty?%>
      <small>Client: <%= @design.client_name %></small>
      <%end%>
    </div>

    <div class='long_desc'> 
      <%= @design.long_desc %><br>
      <% if !@design.client_name.empty?%>
      <small>Client: <%= @design.client_name %></small>
      <%end%>
    </div>

    <div class='design_thumb_container_1'>
      <% photos.first(4).each do |img| %>
        <div class='thumb_box'>
          <%= image_tag img.pic.url, class: 'thumb' %>
        </div>
      <%end%>
    </div>

    <% if photos.length > 4 %>
      <div class='design_thumb_container_2'>
      <% photos.last(photos.length - 4).each do |img| %>
        <div class='thumb_box'>
          <%= image_tag img.pic.url, class: 'thumb' %>
        </div>
      <% end %>
      <% (8 - photos.length).times do |place_holder| %>
        <div class='place_holder_thumb'></div>
      <%end%>
      </div>
    <%end%>

    <%if photos.length > 4 %>
      <div class='design_view_container_2'>
    <% else %>
      <div class='design_view_container'>
    <%end%>
      <%= image_tag @design.gallery.photos.first.pic.url, class: 'highlight_image' unless @design.gallery.photos.first.nil?%>
      </div>
  </div><!-- container --> 
</div><!-- wrapper -->

<div id='design_buttons' style='width: 75px; position: fixed; top: 190px; left: 60px'>
  <%= link_to image_tag('DonPrevButton.png', size: "30x30", id: 'prev_icon', style: 'display: initial;'), design_path(@prev_design), class: 'prev_link' if @prev_design%>
  <%= link_to image_tag('DonNextButton.png', size: "30x30", id: 'next_icon', style: 'display: initial; float: right;'), design_path(@next_design), class: 'next_link' if @next_design%>
  <%= link_to image_tag('hoverDonPrevButton.png', size: "30x30", id: 'hover_prev_icon', style:'display: none;'), design_path(@prev_design), class: 'prev_link' if @prev_design%>
  <%= link_to image_tag('hoverDonNextButton.png', size: "30x30", id: 'hover_next_icon', style:'display: none;'), design_path(@next_design), style: 'float: right; margin-bottom: 100px;', class: 'next_link' if @next_design%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DonDotCom</title>
  <%= favicon_link_tag "df.ico" %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/4.1.1/normalize.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <% if content_for? :about_nav %>
    <div class = "wrapper_blocker">
    </div>
    <%= yield :about_nav %>
  <% elsif content_for? :home_nav %>
    <!-- No pic on this page -->
  <% elsif content_for? :design_show %>
  <div class = "wrapper_blocker">
    <div id="navbar">
      <nav>
        <div class="links show_links">
          <%=link_to 'design', designs_path%>
          <%=link_to 'programming', programs_path%>
          <%=link_to 'blog', blog_index_path%>
          <%=link_to 'about',  about_path %>
        </div>
      </nav>
    </div>
  </div>
    <%=link_to image_tag('sig_pic.png', id:'donpic_down'), root_path %>
  <% else %>
    <div class = "wrapper_blocker transparent"></div>  
    <%=link_to image_tag('sig_pic.png', id:'donpic'), root_path %>
  <%end%>

  <% if content_for? :home_nav %>
     <%= yield :home_nav %>
    </div><!-- #navbar -->
  <% end %>
</header>

<%= yield %>

<footer>
  &copy; 2016 &nbsp; <a href='/about'><span class='don_in_footer'>Don Febbraio</span></a> &nbsp; All Rights Reserved. &nbsp;

  <%=link_to image_tag('email-icon.png', class: 'social_links'), 'mailto:donedesign1@gmail.com?Subject=donfebbraio.com', class: 'Email Me'%>

  <%=link_to image_tag('twitter-icon.png', class: 'social_links', alt: "Twitter Icon"), 'https://twitter.com/Donnief3', target: '_blank', class: 'twitter' %>

  <%=link_to image_tag('github-icon.png', class: 'social_links', alt: "Github Icon"), 'https://github.com/febbraiod', target: '_blank', class: 'github' %>

  <%=link_to image_tag('linkedin-icon.png', class: 'social_links', alt: "LinkedIn Icon"), 'https://www.linkedin.com/in/don-febbraio-10ab0b10a', target: '_blank', class: 'linkedin' %>
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
</body>
</html>

app/views/programs/edit.html.erb
<div class="wrapper">
  <h2>Edit <%=@program.title%></h2>

  <p>would you like to delete this program?<p>
  <%=link_to 'deprogram', program_path(@program), :method => :delete %>
  <br>

  <%= render "program_form" %>

</div>

app/views/programs/index.html.erb
<div id="white_navbar" style='position: fixed; 
  width: 100%;
  top: 75px;
  left: 0px; z-index: 9998;'>
    <nav>
      <div class="links">
        <%=link_to 'design', designs_path%>
        <%=link_to 'programming', programs_path%>
        <%=link_to 'blog', blog_index_path%>
        <%=link_to 'about',  about_path %>
      </div>
    </nav>
</div>

<%= image_tag('blue_matrix.jpg', style: 'width: 100%;') %>
<div class="logo_type_not_home" id='program_logo'>
  <h1>code</h1> 
  <div id='hr_holder__3'><hr></div>
</div>
<div class="program_wrapper__index">
  <% @programs.each_with_index do |program, idx| %>

    <% photos = program.gallery.photos %>

    <div id='prog_head' style='max-width: 650px;'>
      <h3 class='program_title'><%=program.title%></h3>
      <p class='program_desc'><small><%=simple_format(program.description)%></small></p>
    </div>

    <div id='clearfix'>
        <div class='program_thumb_wrapper'>
          <div class='program_thumb_container_1'>
            <% photos.first(4).each do |img| %>
              <div class='thumb_box'>
                <%= image_tag img.pic.url, class: 'program_thumb', data: {index: "#{idx}"} %>
              </div>
            <% end %>
          </div>

          <% if photos.length > 4 %>
            <div class='program_thumb_container_2'>
              <% photos.last(photos.length - 4).each do |img| %>
                <div class='thumb_box'>
                  <%= image_tag img.pic.url, class: 'program_thumb', data: {index: "#{idx}"} %>
                </div> 
              <% end %>

              <% (8 - photos.length).times do |place_holder| %>
                <div class='thumb_box'>
                  <div class='place_holder_thumb'></div>
                </div>
              <%end%>
            </div>
          <%end%>
        </div>

        <div class="program_view_container" id=<%="view_#{idx}"%>>
          <%= image_tag program.gallery.photos.first.pic.url, class: 'highlight_image' %>
        </div>
        <p class='program_links'>Video Demo link: <%= link_to "#{program.title} demo", program.demo %></p>
        <p class='program_links'>App: <%= link_to "#{program.title}", program.link %></p>
    </div>

    <%= link_to 'edit', edit_program_path(program) unless !current_user %> <!-- if admin -->
      
    <% if idx < @programs.length - 1 %>
      <hr id='program_break'>
    <% else %>
      <br>
    <% end %>

  <%end%>
</div>

app/views/programs/new.html.erb
<div class="wrapper">
  <h1>Hi Don!</h1>

  <%= render "program_form" %>

</div>